clear; close all;

Strk = substruct('()',{1,1},...
                 '.','trk',...
                 '()',{2,1},...
                 '.','trkseg',...
                 '()',{4,1},...
                 '.','lat',...
                 '()',{125,1});
test.a.b = struct();   
dynFields = {'a' 'b'};
A = getfield(test,dynFields{:});
B = 10;
A = subsasgn(A,Strk,B);

test = setfield(test,dynFields{:},A);
test.a.b.trk(2).trkseg(4)